# Generated by Django 4.2.7 on 2023-11-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_text_expense_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
